# Generated by Django 6.0.3 on 2026-03-09 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='animal',
            fields=[
                ('animalname', models.CharField(max_length=100)),
                ('animalid', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'animal',
            },
        ),
    ]
