# Generated by Django 6.0.2 on 2026-02-25 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pawportalapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='uname',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
