# Generated by Django 6.0.3 on 2026-03-24 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawportalapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='person',
            fields=[
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('personkey', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'person',
            },
        ),
        migrations.AddField(
            model_name='animal',
            name='animalage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='animallocation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='animal',
            name='aninmalspecies',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='animal',
            name='behaviortype',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='animal',
            name='lastfed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='laswalked',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
