# Generated by Django 6.0.3 on 2026-03-24 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pawportalapp', '0002_person_animal_animalage_animal_animallocation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='aninmalspecies',
            new_name='animalspecies',
        ),
    ]
