# Generated by Django 6.0.3 on 2026-03-24 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pawportalapp', '0003_rename_aninmalspecies_animal_animalspecies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='laswalked',
            new_name='lastwalked',
        ),
    ]
