# Generated by Django 6.0.3 on 2026-03-24 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pawportalapp', '0004_rename_laswalked_animal_lastwalked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='lastwalked',
            new_name='lastwalk',
        ),
    ]
