# Generated by Django 6.0.3 on 2026-04-13 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawportalapp', '0005_rename_lastwalked_animal_lastwalk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='animalspecies',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='behaviortype',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='lastfed',
        ),
        migrations.RemoveField(
            model_name='person',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='person',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='person',
            name='personkey',
        ),
        migrations.AddField(
            model_name='animal',
            name='isadpted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='person',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
