# Generated by Django 6.0.3 on 2026-04-22 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawportalapp', '0006_remove_animal_animalspecies_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='isadpted',
            new_name='isadopted',
        ),
        migrations.AddField(
            model_name='animal',
            name='animalspecies',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
